name: Docs

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**/README.md'
      - '**.yaml'
      - '**.yml'
      - '**.launch'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  cancel:
    name: Cancel Previous Runs
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}

  docs:
    runs-on: ubuntu-20.04
    steps:

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Generate
        run: ./.ci/generate_docs.sh

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./doc/html
          allow_empty_commit: true
          force_orphan: true